// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8xXLC_OVZsaqrtwYtHEo_D0sa7GDsaIE',
    appId: '1:1078682966757:web:f161015e214ad8c922d20c',
    messagingSenderId: '1078682966757',
    projectId: 'healthapp-88751',
    authDomain: 'healthapp-88751.firebaseapp.com',
    storageBucket: 'healthapp-88751.firebasestorage.app',
    measurementId: 'G-T4PDDMWZLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBQlDJM8RHvGaiWYEPHE2IctQzk0PC6O4',
    appId: '1:1078682966757:android:3ed62561bc07a13722d20c',
    messagingSenderId: '1078682966757',
    projectId: 'healthapp-88751',
    storageBucket: 'healthapp-88751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsJDF3xI948Gzc61IYMtiJaWisUQ6LVuk',
    appId: '1:1078682966757:ios:bfa6550606e0422f22d20c',
    messagingSenderId: '1078682966757',
    projectId: 'healthapp-88751',
    storageBucket: 'healthapp-88751.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsJDF3xI948Gzc61IYMtiJaWisUQ6LVuk',
    appId: '1:1078682966757:ios:bfa6550606e0422f22d20c',
    messagingSenderId: '1078682966757',
    projectId: 'healthapp-88751',
    storageBucket: 'healthapp-88751.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8xXLC_OVZsaqrtwYtHEo_D0sa7GDsaIE',
    appId: '1:1078682966757:web:1930fb2cc96ff08222d20c',
    messagingSenderId: '1078682966757',
    projectId: 'healthapp-88751',
    authDomain: 'healthapp-88751.firebaseapp.com',
    storageBucket: 'healthapp-88751.firebasestorage.app',
    measurementId: 'G-6EYNW7ZC72',
  );
}
